spring:
  profiles:
    include: druid
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/*/*.xml
