security:
  oauth2:
    client:
      client-id: ylt2
      client-secret: ylt2
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
      registered-redirect-uri: [http://127.0.0.1:8082/client2/login,http://127.0.0.1:8082/client2/index.html]
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key
server:
  port: 8082
  servlet:
    context-path: /client2
#
#auth-server: http://127.0.0.1:8083/uaa # sso-server地址
#server:
#  port: 8081
#  servlet:
#    context-path: /client1
#security:
#  oauth2:
#    client:
#      client-id: ylt1
#      client-secret: ylt1s
#      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
#      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
#    resource:
#      jwt:
#        key-uri: ${auth-server}/oauth/token_key #解析jwt令牌所需要密钥的地址